import os
import sys
from pathlib import Path

CSV_DIR = os.getenv("CSV_DIR", ".")
VALIDATION_REPORT_PATH = os.getenv("VALIDATION_REPORT_PATH", "validation_report.json")
TABLES = [
  {
    "table_name": "CUSTOMERS",
    "expected_rows": 12000,
    "instructions": "Generate adult customers (age 18-90), realistic US names/addresses, unique email.\nKYC_STATUS in {VERIFIED,PENDING,REJECTED} with 80/15/5 distribution.\nRISK_SCORE between 0 and 100 with 2 decimals.\n",
    "ddl": "CREATE TABLE CUSTOMERS (\n  CUSTOMER_ID BIGINT PRIMARY KEY,\n  FIRST_NAME VARCHAR(50) NOT NULL,\n  LAST_NAME VARCHAR(50) NOT NULL,\n  DATE_OF_BIRTH DATE NOT NULL,\n  EMAIL VARCHAR(120) UNIQUE NOT NULL,\n  PHONE VARCHAR(20),\n  STREET_ADDRESS VARCHAR(120),\n  CITY VARCHAR(60),\n  STATE_CODE CHAR(2),\n  POSTAL_CODE VARCHAR(10),\n  KYC_STATUS VARCHAR(20) NOT NULL,\n  RISK_SCORE DECIMAL(5,2),\n  CREATED_AT TIMESTAMP NOT NULL,\n  UPDATED_AT TIMESTAMP\n);"
  },
  {
    "table_name": "ACCOUNTS",
    "expected_rows": 13000,
    "instructions": "Every CUSTOMER_ID must exist in CUSTOMERS.\nACCOUNT_TYPE in {CHECKING,SAVINGS} with 70/30 split.\nSTATUS in {ACTIVE,DORMANT,CLOSED} with 85/10/5 split.\nAVAILABLE_BALANCE <= BALANCE + OVERDRAFT_LIMIT.\n",
    "ddl": "CREATE TABLE ACCOUNTS (\n  ACCOUNT_ID BIGINT PRIMARY KEY,\n  CUSTOMER_ID BIGINT NOT NULL,\n  ACCOUNT_NUMBER VARCHAR(20) UNIQUE NOT NULL,\n  ACCOUNT_TYPE VARCHAR(20) NOT NULL,\n  CURRENCY_CODE CHAR(3) NOT NULL,\n  BALANCE DECIMAL(18,2) NOT NULL,\n  AVAILABLE_BALANCE DECIMAL(18,2) NOT NULL,\n  STATUS VARCHAR(20) NOT NULL,\n  OPENED_DATE DATE NOT NULL,\n  CLOSED_DATE DATE,\n  BRANCH_CODE VARCHAR(20),\n  OVERDRAFT_LIMIT DECIMAL(18,2),\n  INTEREST_RATE DECIMAL(5,3),\n  CREATED_AT TIMESTAMP NOT NULL,\n  UPDATED_AT TIMESTAMP,\n  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)\n);"
  },
  {
    "table_name": "TRANSACTIONS",
    "expected_rows": 15000,
    "instructions": "Every ACCOUNT_ID must exist in ACCOUNTS.\nTRANSACTION_TYPE in {DEBIT,CREDIT,TRANSFER,FEE,INTEREST}.\nAMOUNT > 0 with right-skew (many small, few large).\n2% rows IS_SUSPICIOUS = true.\nVALUE_DATE should match or be 0-2 days after TRANSACTION_TS date.\n",
    "ddl": "CREATE TABLE TRANSACTIONS (\n  TRANSACTION_ID BIGINT PRIMARY KEY,\n  ACCOUNT_ID BIGINT NOT NULL,\n  TRANSACTION_TS TIMESTAMP NOT NULL,\n  VALUE_DATE DATE NOT NULL,\n  TRANSACTION_TYPE VARCHAR(20) NOT NULL,\n  CHANNEL VARCHAR(20) NOT NULL,\n  AMOUNT DECIMAL(18,2) NOT NULL,\n  CURRENCY_CODE CHAR(3) NOT NULL,\n  DESCRIPTION VARCHAR(200),\n  MERCHANT_NAME VARCHAR(120),\n  MERCHANT_CATEGORY VARCHAR(60),\n  COUNTERPARTY_ACCOUNT VARCHAR(34),\n  STATUS VARCHAR(20) NOT NULL,\n  IS_SUSPICIOUS BOOLEAN NOT NULL,\n  REFERENCE_CODE VARCHAR(40) UNIQUE,\n  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID)\n);"
  },
  {
    "table_name": "LOANS",
    "expected_rows": 10500,
    "instructions": "Every CUSTOMER_ID must exist in CUSTOMERS.\nIf ACCOUNT_ID is present, it must exist in ACCOUNTS and belong to same CUSTOMER_ID.\nLOAN_TYPE in {PERSONAL,HOME,AUTO,SME}.\nOUTSTANDING_AMOUNT between 0 and PRINCIPAL_AMOUNT.\nMaturity date must be after start date by TERM_MONTHS.\n",
    "ddl": "CREATE TABLE LOANS (\n  LOAN_ID BIGINT PRIMARY KEY,\n  CUSTOMER_ID BIGINT NOT NULL,\n  ACCOUNT_ID BIGINT,\n  LOAN_TYPE VARCHAR(30) NOT NULL,\n  PRINCIPAL_AMOUNT DECIMAL(18,2) NOT NULL,\n  OUTSTANDING_AMOUNT DECIMAL(18,2) NOT NULL,\n  INTEREST_RATE DECIMAL(5,3) NOT NULL,\n  TERM_MONTHS INT NOT NULL,\n  START_DATE DATE NOT NULL,\n  MATURITY_DATE DATE NOT NULL,\n  STATUS VARCHAR(20) NOT NULL,\n  COLLATERAL_TYPE VARCHAR(40),\n  CREDIT_SCORE INT,\n  CREATED_AT TIMESTAMP NOT NULL,\n  UPDATED_AT TIMESTAMP,\n  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),\n  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID)\n);"
  },
  {
    "table_name": "LOAN_PAYMENTS",
    "expected_rows": 11000,
    "instructions": "Every LOAN_ID must exist in LOANS; ACCOUNT_ID must exist in ACCOUNTS.\nPAYMENT_AMOUNT = PRINCIPAL_COMPONENT + INTEREST_COMPONENT + PENALTY_COMPONENT.\nPAYMENT_STATUS in {PAID,PENDING,FAILED,LATE}.\nIf status=PAID then PAID_DATE is not null; otherwise PAID_DATE may be null.\n",
    "ddl": "CREATE TABLE LOAN_PAYMENTS (\n  PAYMENT_ID BIGINT PRIMARY KEY,\n  LOAN_ID BIGINT NOT NULL,\n  ACCOUNT_ID BIGINT NOT NULL,\n  PAYMENT_TS TIMESTAMP NOT NULL,\n  DUE_DATE DATE NOT NULL,\n  PAID_DATE DATE,\n  PAYMENT_AMOUNT DECIMAL(18,2) NOT NULL,\n  PRINCIPAL_COMPONENT DECIMAL(18,2) NOT NULL,\n  INTEREST_COMPONENT DECIMAL(18,2) NOT NULL,\n  PENALTY_COMPONENT DECIMAL(18,2) NOT NULL,\n  PAYMENT_METHOD VARCHAR(20) NOT NULL,\n  PAYMENT_STATUS VARCHAR(20) NOT NULL,\n  RECEIPT_NUMBER VARCHAR(40) UNIQUE,\n  CREATED_AT TIMESTAMP NOT NULL,\n  FOREIGN KEY (LOAN_ID) REFERENCES LOANS(LOAN_ID),\n  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID)\n);"
  }
]
SCHEMA_NAME = "Banking"

ROOT_DIR = Path(__file__).resolve().parents[3]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from validation_runtime import run_validation


def main() -> None:
    report = run_validation(
        schema_name=SCHEMA_NAME,
        tables_meta=TABLES,
        csv_dir=CSV_DIR,
        validation_report_path=VALIDATION_REPORT_PATH,
    )
    print(report.get("summary", "Validation completed."))


if __name__ == "__main__":
    main()
